module.exports = {
  siteMetadata: {
    title: `browniebroke.com`,
    description: `Bruno Alla's blog - about programming, and other random things that interest me.`,
    author: `Bruno Alla`,
    siteUrl: `https://browniebroke.com`,
    social: {
      twitter: `_BrunoAlla`,
      stackoverflow: `2261637`,
      github: `browniebroke`,
    },
  },
  plugins: [
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/posts`,
        name: `posts`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/assets`,
        name: `assets`,
      },
    },
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: `gatsby-remark-images`,
            options: {
              maxWidth: 700,
            },
          },
          // {
          //   resolve: `gatsby-remark-responsive-iframe`,
          //   options: {
          //     wrapperStyle: `margin-bottom: 1.0725rem`,
          //   },
          // },
          `gatsby-remark-prismjs`,
          // `gatsby-remark-copy-linked-files`,
          `gatsby-remark-smartypants`,
        ],
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-google-analytics`,
      options: {
        trackingId: `UA-110469572-1`,
      },
    },
    `gatsby-plugin-feed`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `Blog of Bruno alla`,
        short_name: `browniebroke`,
        start_url: `/`,
        background_color: `#ffffff`,
        theme_color: `#666666`,
        display: `minimal-ui`,
        icon: `src/assets/avatar.jpg`,
      },
    },
    `gatsby-plugin-offline`,
    `gatsby-plugin-react-helmet`,
    `gatsby-plugin-styled-components`,
    {
      resolve: `gatsby-plugin-csp`,
      options: {
        directives: {
          'script-src': "'self' 'unsafe-inline' data: www.google-analytics.com",
          'style-src':
            "'self' 'unsafe-inline' fonts.googleapis.com fonts.gstatic.com",
          'img-src': "'self' data: www.google-analytics.com",
        },
      },
    },
    `gatsby-plugin-sitemap`,
    {
      resolve: `gatsby-plugin-typography`,
      options: {
        pathToConfigModule: `src/utils/typography`,
      },
    },
    {
      resolve: `gatsby-plugin-netlify`,
      options: {
        headers: {
          '/*': [
            // The CSP is generated by gatsby-plugin-csp and added to the _headers file in public/ before publish.
            // That is handled by the build script which executes csp-util.js, which looks for the token below.
            'Content-Security-Policy: __REPLACE_ME__',
          ],
        },
        mergeSecurityHeaders: true, // boolean to turn off the default security headers
      },
    },
  ],
}
