name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    uses: browniebroke/github-actions/.github/workflows/ts-lint.yml@2e443406e88fd4e9f1d23620f0908f425220b38a # v1.25.0

  deploy:
    uses: browniebroke/github-actions/.github/workflows/netlify-deploy.yml@2e443406e88fd4e9f1d23620f0908f425220b38a # v1.25.0
    with:
      netlify_site_id: "2d3f146f-3ca0-4651-afa1-4fe16612de76"
      publish_dir: "dist"
    secrets:
      netlify_auth_token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
