name: Upgrader

on:
  workflow_dispatch:
  schedule:
    - cron: "18 */24 * * *"

jobs:
  upgrade:
    uses: browniebroke/github-actions/.github/workflows/npm-upgrade.yml@v1
    secrets:
      gh_pat: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
